# Generated by Django 2.0.13 on 2019-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp_gain', models.IntegerField()),
                ('total_levels_gain', models.IntegerField()),
                ('stats_name', models.CharField(max_length=10)),
            ],
        ),
    ]
