# Generated by Django 2.0.13 on 2019-05-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsmodel',
            name='total_levels_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statsmodel',
            name='total_xp_gain',
            field=models.IntegerField(default=0),
        ),
    ]
