# Generated by Django 2.0.13 on 2019-04-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level_system', '0004_auto_20190418_0236'),
        ('accounts', '0003_profile_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='level_rank',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='level_system.UserLevel'),
        ),
    ]
