# Generated by Django 2.0.13 on 2019-04-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level_system', '0004_auto_20190418_0236'),
        ('accounts', '0005_remove_profile_level_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='level_system.UserLevel'),
        ),
    ]
