# Generated by Django 2.0.13 on 2019-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_level_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level_rank',
        ),
    ]
