# Generated by Django 2.0.13 on 2019-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_level_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level_rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp_threshold',
            field=models.IntegerField(default=100),
        ),
    ]
