# Generated by Django 2.0.13 on 2019-05-17 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_has_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 15, 49, 42, 90181)),
        ),
    ]
