# Generated by Django 2.0.13 on 2019-05-17 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190517_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 15, 51, 41, 841737, tzinfo=utc)),
        ),
    ]
