# Generated by Django 2.0.13 on 2019-04-09 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 14, 53, 18, 582398, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
