# Generated by Django 2.0.13 on 2019-04-10 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190409_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 16, 34, 51, 710492, tzinfo=utc), editable=False),
        ),
    ]
