# Generated by Django 2.0.13 on 2019-04-11 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190411_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 17, 7, 17, 426004, tzinfo=utc), editable=False),
        ),
    ]
