# Generated by Django 2.0.13 on 2019-04-11 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20190411_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 19, 18, 36, 854742, tzinfo=utc), editable=False),
        ),
    ]
