# Generated by Django 2.0.13 on 2019-04-11 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20190411_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 19, 32, 40, 765565, tzinfo=utc), editable=False),
        ),
    ]
