# Generated by Django 2.0.13 on 2019-04-11 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20190411_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 19, 42, 54, 887531, tzinfo=utc), editable=False),
        ),
    ]
