# Generated by Django 2.0.13 on 2019-04-12 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20190411_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 15, 44, 18, 601234, tzinfo=utc), editable=False),
        ),
    ]
