# Generated by Django 2.0.13 on 2019-04-15 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20190412_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 21, 31, 14, 87715, tzinfo=utc), editable=False),
        ),
    ]
