# Generated by Django 2.0.13 on 2019-04-16 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20190415_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 16, 46, 47, 465873, tzinfo=utc), editable=False),
        ),
    ]
