# Generated by Django 2.0.13 on 2019-04-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20190416_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_difficulty',
            field=models.CharField(choices=[('EA', 'Easy'), ('ME', 'Medium'), ('HA', 'Hard'), ('AM', 'Ambitious')], default='EA', max_length=2),
        ),
    ]
