# Generated by Django 2.0.13 on 2019-04-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLevelSystem',
            new_name='UserLevel',
        ),
    ]
