# Generated by Django 2.0.13 on 2019-04-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_system', '0002_auto_20190417_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='xp_threshold',
            field=models.IntegerField(blank=True),
        ),
    ]
