# Generated by Django 2.0.13 on 2019-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_level_rank'),
        ('level_system', '0004_auto_20190418_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
